from math import log2
import random

# function from slide
def myFunction(x):
    if x == 0:
        return 0 
    elif ((log2(x) * 7) % 17) < (x % 13):
        return (x + log2(x)) ** 3
    elif ((log2(x) * 5) % 23) < (x % 19):
        return (log2(x) * 2) ** 3 
    else:
        return (log2(x) ** 2) - x

# Hill climbing algorithm that finds a local maximum starting from a given index.
#B_A : hillClimb algorithm accepts an array and a starting index according to the prompt. 
def hillClimb(arr, start_index):
    if not arr:
        raise ValueError("Empty array")

    local_maximum_index = start_index

    while True:
        # if starting max index is greater than zero go left
        goLeft = local_maximum_index > 0
        # if starting max index is less than array length - 1 go right
        goRight = local_maximum_index < len(arr) - 1

        # if we are going left set left value to arr[local_maximum_index - 1] else -inf
        leftValue = arr[local_maximum_index - 1] if goLeft else float('-inf')

        # if we are going right set right value to arr[local_maximum_index + 1] else -inf
        # at first i thought this should be +inf but that would assume there's always a better value to the right
        # keep negative
        rightValue = arr[local_maximum_index + 1] if goRight else float('-inf')

        currValue = arr[local_maximum_index]

        # if goLeft and left value are greater than the current value slide over the index
        if goLeft and leftValue > currValue:
            local_maximum_index -= 1
            # If we slid over the index, we need to update the current value
            currValue = arr[local_maximum_index]

        # if goRight and right value are greater than the current value slide over the index
        elif goRight and rightValue > currValue:
            local_maximum_index += 1
            # If we slid over the index, we need to update the current value
            currValue = arr[local_maximum_index]

        # Handling the shoulders here - check both directions for possible peaks
        elif ((goLeft and leftValue == currValue) or 
              (goRight and rightValue == currValue)):
            
            foundBetter = False
            
            # Check left shoulder first
            # if the values are the same 
            if goLeft and leftValue == currValue:
                # Look ahead through the left shoulder
                tempIndex = local_maximum_index - 1
                while tempIndex >= 0 and arr[tempIndex] == currValue:
                    tempIndex -= 1
                # If there's a better number in the left shoulder, move left
                if tempIndex >= 0 and arr[tempIndex] > currValue:
                    local_maximum_index -= 1
                    foundBetter = True
            
            # Check right shoulder
            if not foundBetter and goRight and rightValue == currValue:
                # Look ahead through the right shoulder
                tempIndex = local_maximum_index + 1
                while tempIndex < len(arr) and arr[tempIndex] == currValue:
                    tempIndex += 1
                # If there's a better number in the right shoulder, move right
                if tempIndex < len(arr) and arr[tempIndex] > currValue:
                    local_maximum_index += 1
                    foundBetter = True
            
            # If no improvement found through shoulders, find leftmost position
            if not foundBetter:
                # Find the leftmost position
                shoulderStart = local_maximum_index
                while shoulderStart > 0 and arr[shoulderStart - 1] == currValue:
                    shoulderStart -= 1
                local_maximum_index = shoulderStart
                # B_B: hillClimb algorithm returns an index and a value of the local maximum according to the exact specifications of the prompt.
                return local_maximum_index, arr[local_maximum_index]
        else:
            # No neighbors or we have the best number
            # B_B: hillClimb algorithm returns an index and a value of the local maximum according to the exact specifications of the prompt. 
            return local_maximum_index, arr[local_maximum_index]

def lasVegasAlgo(arr):
    # Find the global maximum value in the array
    targetValue = max(arr)  
     # Counter for how many attempts we've made
    tries = 0 
    
    # Las Vegas has an unlimited runtime and doesn't stop until it has the answer
    while True:  
        # Increment attempt counter
        tries += 1  

        # Pick a random starting position making sure my range is the whole array
        # start_index = random.randrange(0, len(arr))

        # Run hill climbing from this random starting point
        # C : The array generated by myFunction and a random starting index of the correct amount are
        # passed into the hillClimb function multiple times

        # Pick a random starting position making sure my range is the whole array
        start_index = random.randrange(0, len(arr))

        peakIndex, peakValleyValue = hillClimb(arr, start_index)
        
        # Check if we found the global maximum
        if peakValleyValue == targetValue:
            # Return the results if we found the global maximum
            return peakIndex, peakValleyValue, tries

# I included the test cases here
# D: hillClimb algorithm passes all test cases.
def testHillClimb():
    print("Testing hillClimb function with hardcoded values:")
    
    # hillClimb([6,5,5,5,4,3,2],5) should return the index 0 and the value 6 
    peakIndex, peakValue = hillClimb([6,5,5,5,4,3,2], 5)
    print(f"hillClimb([6,5,5,5,4,3,2], 5) -> index: {peakIndex}, value: {peakValue}")
    
    # hillClimb([2,5,5,5,4,3,2],5) should return the index 1 and the value 5.
    peakIndex, peakValue = hillClimb([2,5,5,5,4,3,2], 5)
    print(f"hillClimb([2,5,5,5,4,3,2], 5) -> index: {peakIndex}, value: {peakValue}")

    # hillClimb([1,2,3,4,3,2,6,8,4,3],3) should return the index 3 and the value 4.
    peakIndex, peakValue = hillClimb([1,2,3,4,3,2,6,8,4,3], 3)
    print(f"hillClimb([1,2,3,4,3,2,6,8,4,3], 3) -> index: {peakIndex}, value: {peakValue}")


    # hillClimb([1,2,3,4,3,2,6,8,4,3],3) should return the index 6 and the value 7.
    peakIndex, peakValue = hillClimb([1,2,3,4,5,6,7], 2)
    print(f"hillClimb([1,2,3,4,5,6,7], 2) -> index: {peakIndex}, value: {peakValue}")

def main():
    # Test the hillClimb function first
    # Uncomment to see
    testHillClimb()
    
    # Create an array of 10000 values using myFunction
    # A: Generated array to pass into the hillClimb function using myFunction.
    arr = []
    for x in range(10000):
        arr.append(myFunction(x))  
    
    # Run Las Vegas hill climbing algorithm
    lasVegasIndex, lasVegasValue, lasVegasTries = lasVegasAlgo(arr)
    # # E: Program prints the amount of times it ran the hillClimb function and what the best local maximum discovered was along with the global maximum.
    print(f"After {lasVegasTries} tries, the greatest local maximum discovered was {int(lasVegasValue)} which was the global maximum and was located at index {lasVegasIndex}.")


main()